import Head from 'next/head';
import { useRouter } from 'next/router';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import en from '@/locales/en';
import es from '@/locales/es';

const inter = Inter({ subsets: ['latin'] });

function Bullet({ isCorrect = false }: { isCorrect?: boolean }) {
    return (
        <svg
            className={`${isCorrect ? styles.correct : ''} ${styles.svgIcon}`}
            xmlns="http://www.w3.org/2000/svg"
            width="29"
            height="29"
            viewBox="0 0 29 29"
        >
            <circle cx="14.5996" cy="14.7192" r="12.375" />
        </svg>
    );
}

function LanguageSwitch() {
    const router = useRouter();
    const { locale } = router;

    const changeLanguage = (e: any) => {
        const locale = e.target.value;
        router.push(router.pathname, router.asPath, { locale });
    };

    return (
        <select onChange={changeLanguage} defaultValue={locale}>
            <option value="en">English</option>
            <option value="es">Español</option>
        </select>
    );
}

export default function Home() {
    const router = useRouter();
    const { locale } = router;
    const t = locale === 'en' ? en : es;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div style={{ marginBottom: '70px' }}>
                    <LanguageSwitch />
                </div>
                <div className={`${styles.container}`}>
                    <p className={`${styles.title}`}>{t.title}</p>
                    <ul>
                        {t.questions.map((question, index) => {
                            return (
                                <li key={index} className={`${styles.question}`}>
                                    <Bullet isCorrect={index === 2 ? true : false} />
                                    {question}
                                </li>
                            );
                        })}
                    </ul>
                </div>
            </main>
        </>
    );
}
