import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const [key, setKey] = useState(0);
    useEffect(() => {
        const id = setTimeout(() => {
            setKey((previous) => previous + 1);
        }, 4320);
        return () => clearTimeout(id);
    }, [key]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div key={key} className={`${styles.container}`}>
                    <p>QUESTION???</p>
                    <ul>
                        <li className={`${styles.question}`}>question 1</li>
                        <li className={`${styles.question}`}>question 2</li>
                        <li className={`${styles.question}`}>question 3</li>
                    </ul>
                </div>
            </main>
        </>
    );
}
